name: GitHub Actions Demo
on:
  push:
    branches:
      - main

env:
  node-version: 16
  PROJECT_ID: "gh-actions-express-app"
  SERVER_NAME: "my_server"

jobs:
  build-push-docker-hub:
    name: Build and push to docker hub
    if: startsWith(github.event.head_commit.message, '[mark-') == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version}}

      - name: Get app version from commit message
        id: version-info
        if: startsWith(github.event.head_commit.message, '[mark-')
        run: >-
          echo "APP_VERSION=$(
            echo ${{github.event.head_commit.message}} |
            sed -n 's/.*\[mark-\(v[0-9][0-9\.]*\)\].*/\1/p'
          )" >> $GITHUB_OUTPUT
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/${{ env.SERVER_NAME }}.key
          sudo chmod 600 ~/.ssh/${{ env.SERVER_NAME }}.key
        shell: bash
      - name: Scan the public ssh host keys
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        shell: bash

      - name: Create SSH config
        run: |
          cat >>~/.ssh/config <<END
          Host ${{ env.SERVER_NAME }}
            HostName ${{ secrets.SSH_HOST }}
            Port 22
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/${{ env.SERVER_NAME }}.key
          END
        shell: bash

      - name: Move docker-compose file to vm
        run: scp -i ~/.ssh/${{ env.SERVER_NAME }}.key docker-compose.yml deploy.sh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/charp
