name: GitHub Actions Demo
on:
  push:
    branches:
      - main

env:
  node-version: 16
  USER_NAME: "charupraneeth"
  PROJECT_ID: "gh-actions-express-app"

jobs:
  build-push-docker-hub:
    name: Build and push to docker hub
    if: startsWith(github.event.head_commit.message, '[mark-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version}}

      - name: Get app version from commit message
        id: version-info
        run: >-
          echo "APP_VERSION=$(
            echo ${{github.event.head_commit.message}} |
            sed -n 's/.*\[mark-\(v[0-9][0-9\.]*\)\].*/\1/p'
          )" >> $GITHUB_OUTPUT

      - name: Install NPM dependencies
        run: |
          npm ci

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Echo env
        run: echo "$env"

      - name: Echo steps
        run: echo "$steps"
      # - name: Build the Docker image
      #   run: docker build --tag ${{ env.USER_NAME }}/${{ env.PROJECT_ID }}:${{ steps.version-info.outputs.APP_VERSION }} .

      # - name: Add latest tag
      #   run: docker tag ${{ env.USER_NAME }}/${{ env.PROJECT_ID }}:${{ steps.version-info.outputs.APP_VERSION }} ${{ env.USER_NAME }}/${{ env.PROJECT_ID }}:latest

      # - name: Push the Docker image to Docker hub
      #   run: docker push ${{ env.USER_NAME }}/${{ env.PROJECT_ID }} --all-tags
